# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIzMNA5_dAUygtYoahjw8GHjAz25YdYu
"""

import pandas as pd
from lifelines import CoxPHFitter

data = pd.read_csv('../Data/coxregression_agemgpena_utf8.csv')

data.columns = ["Sample", "Grade", "Survival", "Status", "Age", "Pena"]

data = data[data['Survival'].notna()]

# Convert 'Grade' column into binary categories
data["Grade"] = data["Grade"].replace(1, 0)
data["Grade"] = data["Grade"].replace(2, 0)
data["Grade"] = data["Grade"].replace(3, 1)

data = data.drop("Sample", axis=1)

cph = CoxPHFitter()
cph.fit(data, duration_col='Survival', event_col='Status')
cph.print_summary()
