# -*- coding: utf-8 -*-
"""km.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJXAyilAJ9XX5uXbR26fnpRb-xTfmhnv
"""

import pandas as pd
from lifelines import KaplanMeierFitter
from lifelines.statistics import logrank_test, multivariate_logrank_test
import matplotlib.pyplot as plt

data = pd.read_csv('kaplanmeier_mg.csv', encoding='latin-1')

data['Grade'] = pd.Categorical(data['Grade'], categories=[1, 2, 3], ordered=True)
data.dropna(inplace=True)
data['Survival'] = data['Survival'].fillna(data['Survival'].mean())

# Kaplan-Meier (KM) Curve & Log-Rank (LR) Test - Non-Grouped Grades
kmf = KaplanMeierFitter()
median_survival_time_non_grouped = {}

plt.figure(figsize=(8, 6))

for grade in sorted(data['Grade'].unique()):
    mask = data['Grade'] == grade
    kmf.fit(data.loc[mask, 'Survival'], event_observed=data.loc[mask, 'Status'])
    kmf.plot(label=f'Grade {grade}')
    median_survival_time_non_grouped[f'Grade {grade}'] = kmf.median_survival_time_

plt.title('Kaplan-Meier Curves for Canine Mammary Tumors (Non-Grouped)', fontsize=14)
plt.xlabel('Time (days)', fontsize=12)
plt.ylabel('Survival Probability', fontsize=12)
plt.legend(title='Tumor Grade', fontsize=10)
plt.show()

print('Median Survival Time by Non-Grouped Grade:')
for grade, median_time in median_survival_time_non_grouped.items():
    print(f'{grade}: {median_time:.2f} days')

results_non_grouped = logrank_test(data['Survival'], data['Grade'])
print('Log-Rank Test Results (Non-Grouped):')
print(results_non_grouped.summary)

# KM & LR - Grouped Grades (Grades 1 and 2 Combined vs Grade 3)
data['Grade_Grouped'] = data['Grade'].apply(lambda x: 1 if x in [1, 2] else 3)
kmf_grouped = KaplanMeierFitter()
median_survival_time_grouped = {}

plt.figure(figsize=(8, 6))

mask_grouped_1_2 = data['Grade_Grouped'] == 1
kmf_grouped.fit(data.loc[mask_grouped_1_2, 'Survival'], event_observed=data.loc[mask_grouped_1_2, 'Status'])
kmf_grouped.plot(label='Grade 1-2')
median_survival_time_grouped['Grade 1-2'] = kmf_grouped.median_survival_time_

mask_grouped_3 = data['Grade_Grouped'] == 3
kmf_grouped.fit(data.loc[mask_grouped_3, 'Survival'], event_observed=data.loc[mask_grouped_3, 'Status'])
kmf_grouped.plot(label='Grade 3')
median_survival_time_grouped['Grade 3'] = kmf_grouped.median_survival_time_

plt.title('Kaplan-Meier Curves for Canine Mammary Tumors (Grouped Grades)', fontsize=14)
plt.xlabel('Time (days)', fontsize=12)
plt.ylabel('Survival Probability', fontsize=12)
plt.legend(title='Tumor Grade', fontsize=10)
plt.show()

print('Median Survival Time by Grouped Grade:')
for grade, median_time in median_survival_time_grouped.items():
    print(f'{grade}: {median_time:.2f} days')

results_grouped = logrank_test(data['Survival'], data['Grade_Grouped'])
print('Log-Rank Test Results (Grouped):')
print(results_grouped.summary)